---
openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /login:
    post:
      summary: Login
      operationId: login_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentialsRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /register:
    post:
      summary: Register
      operationId: register_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /whoami:
    get:
      summary: Whoami
      operationId: whoami_whoami_get
      parameters:
        - description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          required: false
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          name: authentication
          in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WhoAmIResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /payment-link/create:
    post:
      summary: Create Payment Link
      operationId: create-payment-link_create-payment-link_post
      parameters:
        - name: authentication
          in: header
          required: false
          description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentLinkRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentLinkResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /payment-link/{link}:
    get:
      summary: Get Payment Link
      operationId: get-payment-link_get-payment-link_get
      parameters:
        - name: authentication
          in: header
          required: false
          description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
        - name: link
          in: path
          required: true
          description: Payment Link URL
          schema:
            title: Link
            type : string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPaymentLinkResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /payment-link/pay:
    post:
      summary: Pay Payment Link
      operationId: pay-payment-link_pay-payment-link_post
      parameters:
        - name: authentication
          in: header
          required: false
          description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayPaymentLinkRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayPaymentLinkResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
                
components:
  schemas:
    LoginCredentialsRequest:
      title: LoginCredentialsRequest
      required:
        - username
        - password
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
    LoginResponse:
      title: LoginResponse
      required:
        - success
        - access_token
        - refresh_token
      type: object
      properties:
        success:
          title: Success
          type: boolean
        access_token:
          title: Access Token
          type: string
        refresh_token:
          title: Refresh Token
          type: string
    MessageResponse:
      title: MessageResponse
      required:
        - success
        - message
      type: object
      properties:
        success:
          title: Success
          type: boolean
        message:
          title: Message
          type: string
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - username
        - password
        - password2
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        password2:
          title: Password2
          type: string
    WhoAmIResponse:
      title: WhoAmIResponse
      required:
        - success
        - username
      type: object
      properties:
        success:
          title: Success
          type: boolean
        username:
          title: Username
          type: string
    CreatePaymentLinkRequest:
      title: CreatePaymentLinkRequest
      required:
        - nominal
      type: object
      properties:
        nominal:
          title: Nominal
          type: integer
    CreatePaymentLinkResponse:
      title: CreatePaymentLinkResponse
      required:
        - link
        - nominal
      type: object
      properties:
        nominal:
          title: Nominal
          type: integer
        link:
          title: Link
          type: string
    GetPaymentLinkResponse:
      title: GetPaymentLinkResponse
      required:
        - code
        - nominal
      type: object
      properties:
        code:
          title: Code
          type: string
        nominal:
          title: Nominal
          type: integer
    PayPaymentLinkRequest:
      title: PayPaymentLinkRequest
      required:
        - link
      type: object
      properties:
        link:
          title: Link
          type: string
    PayPaymentLinkResponse:
      title: PayPaymentLinkResponse
      required:
        - message
      type: object
      properties:
        message:
          title: Message
          type: string