---
openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /login:
    post:
      summary: Login
      operationId: login_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentialsRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /register:
    post:
      summary: Register
      operationId: register_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /whoami:
    get:
      summary: Whoami
      operationId: whoami_whoami_get
      parameters:
        - description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          required: false
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          name: authentication
          in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WhoAmIResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /transfer/instant:
    post:
      summary: Instant Transfer
      operationId: instant_transfer_transfer_instant_post
      parameters:
        - description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          required: false
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          name: authentication
          in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstantTransferRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstantTransferResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /transfer/scheduled:
    post:
      summary: Scheduled Transfer
      operationId: scheduled_transfer_transfer_scheduled_post
      parameters:
        - description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          required: false
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          name: authentication
          in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduledTransferRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduledTransferResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /transfer/check-target:
    post:
      summary: Check Target
      operationId: check_target_transfer_check_target_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TargetCheckRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetCheckResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    LoginCredentialsRequest:
      title: LoginCredentialsRequest
      required:
        - username
        - password
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
    LoginResponse:
      title: LoginResponse
      required:
        - success
        - access_token
        - refresh_token
      type: object
      properties:
        success:
          title: Success
          type: boolean
        access_token:
          title: Access Token
          type: string
        refresh_token:
          title: Refresh Token
          type: string
    MessageResponse:
      title: MessageResponse
      required:
        - success
        - message
      type: object
      properties:
        success:
          title: Success
          type: boolean
        message:
          title: Message
          type: string
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - username
        - password
        - password2
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        password2:
          title: Password2
          type: string
    WhoAmIResponse:
      title: WhoAmIResponse
      required:
        - success
        - username
      type: object
      properties:
        success:
          title: Success
          type: boolean
        username:
          title: Username
          type: string
    InstantTransferRequest:
      title: InstantTransferRequest
      required:
        - access_token
        - target_account
        - nominal
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        target_account:
          title: Target Account
          type: string
        nominal:
          title: Nominal
          type: integer
    InstantTransferResponse:
      title: InstantTransferResponse
      required:
        - target_account
        - target_name
        - time
      type: object
      properties:
        target_account:
          title: Target Account
          type: string
        target_name:
          title: Target Name
          type: string
        time:
          title: Time
          type: string
    ScheduledTransferRequest:
      title: ScheduledTransferRequest
      required:
        - access_token
        - target_account
        - nominal
        - schedule
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        target_account:
          title: Target Account
          type: string
        nominal:
          title: Nominal
          type: string
        schedule:
          title: Schedule
          type: string
    ScheduledTransferResponse:
      title: ScheduledTransferResponse
      required:
        - target_account
        - target_name
        - request_time
        - transfer_time
      type: object
      properties:
        target_account:
          title: Target Account
          type: string
        target_name:
          title: Target Name
          type: string
        request_time:
          title: Request Time
          type: string
        transfer_time:
          title: Transfer Time
          type: string
    TargetCheckRequest:
      title: TargetCheckRequest
      required:
        - target_account
      type: object
      properties:
        target_account:
          title: Target Account
          type: string
    TargetCheckResponse:
      title: TargetCheckResponse
      required:
        - target_account
        - target_name
      type: object
      properties:
        target_account:
          title: Target Account
          type: string
        target_name:
          title: Target Name
          type: string
